install libs and doc to different location; names of pc files for data and thirdparty projects changed

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -20968,6 +20968,7 @@ echo "$as_me:$LINENO: checking whether project Blas is available" >&5
 echo $ECHO_N "checking whether project Blas is available... $ECHO_C" >&6
 
 coin_has_blas=notGiven
+coin_have_project_dir=no
 
 # check if user wants to skip project in any case
 
@@ -20985,6 +20986,7 @@ fi
 if test $coin_has_blas != skipping; then
   if test $PACKAGE_TARNAME = blas; then
     coin_has_blas=.
+    coin_have_project_dir=yes
   fi
 
 
@@ -21017,7 +21019,7 @@ if test $coin_has_blas = notGiven; then
 
     # let's assume that when installing into $prefix, then the user may have installed some other coin projects there before, so it's worth to have a look into there
     if test -d "$prefix"; then
-      PKG_CONFIG_PATH="$prefix/lib/ThirdParty/pkgconfig:$PKG_CONFIG_PATH"
+      PKG_CONFIG_PATH="$prefix/lib/pkgconfig:$PKG_CONFIG_PATH"
     fi
 
 
@@ -21029,7 +21031,7 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
        fi
-       PKG_CONFIG_PATH="$withval/lib/ThirdParty/pkgconfig:$PKG_CONFIG_PATH"
+       PKG_CONFIG_PATH="$withval/lib/pkgconfig:$PKG_CONFIG_PATH"
 
 fi;
 
@@ -21038,16 +21040,16 @@ fi;
     export PKG_CONFIG_PATH
 
 if test -n "$PKG_CONFIG" ; then
-  if $PKG_CONFIG --exists "blas"; then
-    BLAS_VERSION=`$PKG_CONFIG --modversion "blas" 2>/dev/null`
-    coin_has_blas="$BLAS_VERSION"
+  if $PKG_CONFIG --exists "coinblas"; then
+    COINBLAS_VERSION=`$PKG_CONFIG --modversion "coinblas" 2>/dev/null`
+    coin_has_blas="$COINBLAS_VERSION"
   else
-    BLAS_PKG_ERRORS=`$PKG_CONFIG $pkg_short_errors --errors-to-stdout --print-errors "blas"`
+    COINBLAS_PKG_ERRORS=`$PKG_CONFIG $pkg_short_errors --errors-to-stdout --print-errors "coinblas"`
 
   fi
 else
-  { { echo "$as_me:$LINENO: error: \"Cannot check for existance of module Blas without pkg-config\"" >&5
-echo "$as_me: error: \"Cannot check for existance of module Blas without pkg-config\"" >&2;}
+  { { echo "$as_me:$LINENO: error: \"Cannot check for existance of module coinblas without pkg-config\"" >&5
+echo "$as_me: error: \"Cannot check for existance of module coinblas without pkg-config\"" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -21059,14 +21061,13 @@ fi
 # if not found yet, check if project is available in present directory
 if test "$coin_has_blas" = notGiven; then
   if test -d $srcdir/ThirdParty/Blas; then
-    coin_pkg_is_here=no
     for i in $srcdir/ThirdParty/Blas/daxpy.f; do
          if test -r $i; then
-           coin_pkg_is_here=yes
+           coin_have_project_dir=yes
          fi
        done
 
-    if test $coin_pkg_is_here = yes; then
+    if test $coin_have_project_dir = yes; then
       coin_has_blas=ThirdParty/Blas
     fi
   fi
@@ -21077,9 +21078,7 @@ echo "${ECHO_T}$coin_has_blas" >&6
 
 echo "$as_me:$LINENO: checking whether project Blas need to be configured" >&5
 echo $ECHO_N "checking whether project Blas need to be configured... $ECHO_C" >&6
-if test "$coin_has_blas" != skipping &&
-   test "$coin_has_blas" != notGiven &&
-   test "$coin_has_blas" != installed; then
+if test "$coin_have_project_dir" = yes ; then
 
   if test -r $srcdir/ThirdParty/Blas/configure; then
     coin_subdirs="$coin_subdirs ThirdParty/Blas"
@@ -21103,6 +21102,7 @@ echo "$as_me:$LINENO: checking whether project Lapack is available" >&5
 echo $ECHO_N "checking whether project Lapack is available... $ECHO_C" >&6
 
 coin_has_lapack=notGiven
+coin_have_project_dir=no
 
 # check if user wants to skip project in any case
 
@@ -21120,6 +21120,7 @@ fi
 if test $coin_has_lapack != skipping; then
   if test $PACKAGE_TARNAME = lapack; then
     coin_has_lapack=.
+    coin_have_project_dir=yes
   fi
 
 
@@ -21152,7 +21153,7 @@ if test $coin_has_lapack = notGiven; then
 
     # let's assume that when installing into $prefix, then the user may have installed some other coin projects there before, so it's worth to have a look into there
     if test -d "$prefix"; then
-      PKG_CONFIG_PATH="$prefix/lib/ThirdParty/pkgconfig:$PKG_CONFIG_PATH"
+      PKG_CONFIG_PATH="$prefix/lib/pkgconfig:$PKG_CONFIG_PATH"
     fi
 
 
@@ -21164,7 +21165,7 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
        fi
-       PKG_CONFIG_PATH="$withval/lib/ThirdParty/pkgconfig:$PKG_CONFIG_PATH"
+       PKG_CONFIG_PATH="$withval/lib/pkgconfig:$PKG_CONFIG_PATH"
 
 fi;
 
@@ -21173,16 +21174,16 @@ fi;
     export PKG_CONFIG_PATH
 
 if test -n "$PKG_CONFIG" ; then
-  if $PKG_CONFIG --exists "lapack"; then
-    LAPACK_VERSION=`$PKG_CONFIG --modversion "lapack" 2>/dev/null`
-    coin_has_lapack="$LAPACK_VERSION"
+  if $PKG_CONFIG --exists "coinlapack"; then
+    COINLAPACK_VERSION=`$PKG_CONFIG --modversion "coinlapack" 2>/dev/null`
+    coin_has_lapack="$COINLAPACK_VERSION"
   else
-    LAPACK_PKG_ERRORS=`$PKG_CONFIG $pkg_short_errors --errors-to-stdout --print-errors "lapack"`
+    COINLAPACK_PKG_ERRORS=`$PKG_CONFIG $pkg_short_errors --errors-to-stdout --print-errors "coinlapack"`
 
   fi
 else
-  { { echo "$as_me:$LINENO: error: \"Cannot check for existance of module Lapack without pkg-config\"" >&5
-echo "$as_me: error: \"Cannot check for existance of module Lapack without pkg-config\"" >&2;}
+  { { echo "$as_me:$LINENO: error: \"Cannot check for existance of module coinlapack without pkg-config\"" >&5
+echo "$as_me: error: \"Cannot check for existance of module coinlapack without pkg-config\"" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -21194,14 +21195,13 @@ fi
 # if not found yet, check if project is available in present directory
 if test "$coin_has_lapack" = notGiven; then
   if test -d $srcdir/ThirdParty/Lapack; then
-    coin_pkg_is_here=no
     for i in $srcdir/ThirdParty/Lapack/LAPACK/SRC/dlarf.f; do
          if test -r $i; then
-           coin_pkg_is_here=yes
+           coin_have_project_dir=yes
          fi
        done
 
-    if test $coin_pkg_is_here = yes; then
+    if test $coin_have_project_dir = yes; then
       coin_has_lapack=ThirdParty/Lapack
     fi
   fi
@@ -21212,9 +21212,7 @@ echo "${ECHO_T}$coin_has_lapack" >&6
 
 echo "$as_me:$LINENO: checking whether project Lapack need to be configured" >&5
 echo $ECHO_N "checking whether project Lapack need to be configured... $ECHO_C" >&6
-if test "$coin_has_lapack" != skipping &&
-   test "$coin_has_lapack" != notGiven &&
-   test "$coin_has_lapack" != installed; then
+if test "$coin_have_project_dir" = yes ; then
 
   if test -r $srcdir/ThirdParty/Lapack/configure; then
     coin_subdirs="$coin_subdirs ThirdParty/Lapack"
@@ -21238,6 +21236,7 @@ echo "$as_me:$LINENO: checking whether project Sample is available" >&5
 echo $ECHO_N "checking whether project Sample is available... $ECHO_C" >&6
 
 coin_has_sample=notGiven
+coin_have_project_dir=no
 
 # check if user wants to skip project in any case
 
@@ -21255,6 +21254,7 @@ fi
 if test $coin_has_sample != skipping; then
   if test $PACKAGE_TARNAME = sample; then
     coin_has_sample=.
+    coin_have_project_dir=yes
   fi
 
 
@@ -21287,7 +21287,7 @@ if test $coin_has_sample = notGiven; then
 
     # let's assume that when installing into $prefix, then the user may have installed some other coin projects there before, so it's worth to have a look into there
     if test -d "$prefix"; then
-      PKG_CONFIG_PATH="$prefix/lib/Data/pkgconfig:$PKG_CONFIG_PATH"
+      PKG_CONFIG_PATH="$prefix/lib/pkgconfig:$PKG_CONFIG_PATH"
     fi
 
 
@@ -21299,7 +21299,7 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
        fi
-       PKG_CONFIG_PATH="$withval/lib/Data/pkgconfig:$PKG_CONFIG_PATH"
+       PKG_CONFIG_PATH="$withval/lib/pkgconfig:$PKG_CONFIG_PATH"
 
 fi;
 
@@ -21308,16 +21308,16 @@ fi;
     export PKG_CONFIG_PATH
 
 if test -n "$PKG_CONFIG" ; then
-  if $PKG_CONFIG --exists "sample"; then
-    SAMPLE_VERSION=`$PKG_CONFIG --modversion "sample" 2>/dev/null`
-    coin_has_sample="$SAMPLE_VERSION"
+  if $PKG_CONFIG --exists "coindatasample"; then
+    COINDATASAMPLE_VERSION=`$PKG_CONFIG --modversion "coindatasample" 2>/dev/null`
+    coin_has_sample="$COINDATASAMPLE_VERSION"
   else
-    SAMPLE_PKG_ERRORS=`$PKG_CONFIG $pkg_short_errors --errors-to-stdout --print-errors "sample"`
+    COINDATASAMPLE_PKG_ERRORS=`$PKG_CONFIG $pkg_short_errors --errors-to-stdout --print-errors "coindatasample"`
 
   fi
 else
-  { { echo "$as_me:$LINENO: error: \"Cannot check for existance of module Sample without pkg-config\"" >&5
-echo "$as_me: error: \"Cannot check for existance of module Sample without pkg-config\"" >&2;}
+  { { echo "$as_me:$LINENO: error: \"Cannot check for existance of module coindatasample without pkg-config\"" >&5
+echo "$as_me: error: \"Cannot check for existance of module coindatasample without pkg-config\"" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -21329,10 +21329,9 @@ fi
 # if not found yet, check if project is available in present directory
 if test "$coin_has_sample" = notGiven; then
   if test -d $srcdir/Data/Sample; then
-    coin_pkg_is_here=no
-     coin_pkg_is_here=yes
+     coin_have_project_dir=yes
 
-    if test $coin_pkg_is_here = yes; then
+    if test $coin_have_project_dir = yes; then
       coin_has_sample=Data/Sample
     fi
   fi
@@ -21343,9 +21342,7 @@ echo "${ECHO_T}$coin_has_sample" >&6
 
 echo "$as_me:$LINENO: checking whether project Sample need to be configured" >&5
 echo $ECHO_N "checking whether project Sample need to be configured... $ECHO_C" >&6
-if test "$coin_has_sample" != skipping &&
-   test "$coin_has_sample" != notGiven &&
-   test "$coin_has_sample" != installed; then
+if test "$coin_have_project_dir" = yes ; then
 
   if test -r $srcdir/Data/Sample/configure; then
     coin_subdirs="$coin_subdirs Data/Sample"
@@ -21369,6 +21366,7 @@ echo "$as_me:$LINENO: checking whether project Netlib is available" >&5
 echo $ECHO_N "checking whether project Netlib is available... $ECHO_C" >&6
 
 coin_has_netlib=notGiven
+coin_have_project_dir=no
 
 # check if user wants to skip project in any case
 
@@ -21386,6 +21384,7 @@ fi
 if test $coin_has_netlib != skipping; then
   if test $PACKAGE_TARNAME = netlib; then
     coin_has_netlib=.
+    coin_have_project_dir=yes
   fi
 
 
@@ -21418,7 +21417,7 @@ if test $coin_has_netlib = notGiven; then
 
     # let's assume that when installing into $prefix, then the user may have installed some other coin projects there before, so it's worth to have a look into there
     if test -d "$prefix"; then
-      PKG_CONFIG_PATH="$prefix/lib/Data/pkgconfig:$PKG_CONFIG_PATH"
+      PKG_CONFIG_PATH="$prefix/lib/pkgconfig:$PKG_CONFIG_PATH"
     fi
 
 
@@ -21430,7 +21429,7 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
        fi
-       PKG_CONFIG_PATH="$withval/lib/Data/pkgconfig:$PKG_CONFIG_PATH"
+       PKG_CONFIG_PATH="$withval/lib/pkgconfig:$PKG_CONFIG_PATH"
 
 fi;
 
@@ -21439,16 +21438,16 @@ fi;
     export PKG_CONFIG_PATH
 
 if test -n "$PKG_CONFIG" ; then
-  if $PKG_CONFIG --exists "netlib"; then
-    NETLIB_VERSION=`$PKG_CONFIG --modversion "netlib" 2>/dev/null`
-    coin_has_netlib="$NETLIB_VERSION"
+  if $PKG_CONFIG --exists "coindatanetlib"; then
+    COINDATANETLIB_VERSION=`$PKG_CONFIG --modversion "coindatanetlib" 2>/dev/null`
+    coin_has_netlib="$COINDATANETLIB_VERSION"
   else
-    NETLIB_PKG_ERRORS=`$PKG_CONFIG $pkg_short_errors --errors-to-stdout --print-errors "netlib"`
+    COINDATANETLIB_PKG_ERRORS=`$PKG_CONFIG $pkg_short_errors --errors-to-stdout --print-errors "coindatanetlib"`
 
   fi
 else
-  { { echo "$as_me:$LINENO: error: \"Cannot check for existance of module Netlib without pkg-config\"" >&5
-echo "$as_me: error: \"Cannot check for existance of module Netlib without pkg-config\"" >&2;}
+  { { echo "$as_me:$LINENO: error: \"Cannot check for existance of module coindatanetlib without pkg-config\"" >&5
+echo "$as_me: error: \"Cannot check for existance of module coindatanetlib without pkg-config\"" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -21460,10 +21459,9 @@ fi
 # if not found yet, check if project is available in present directory
 if test "$coin_has_netlib" = notGiven; then
   if test -d $srcdir/Data/Netlib; then
-    coin_pkg_is_here=no
-     coin_pkg_is_here=yes
+     coin_have_project_dir=yes
 
-    if test $coin_pkg_is_here = yes; then
+    if test $coin_have_project_dir = yes; then
       coin_has_netlib=Data/Netlib
     fi
   fi
@@ -21474,9 +21472,7 @@ echo "${ECHO_T}$coin_has_netlib" >&6
 
 echo "$as_me:$LINENO: checking whether project Netlib need to be configured" >&5
 echo $ECHO_N "checking whether project Netlib need to be configured... $ECHO_C" >&6
-if test "$coin_has_netlib" != skipping &&
-   test "$coin_has_netlib" != notGiven &&
-   test "$coin_has_netlib" != installed; then
+if test "$coin_have_project_dir" = yes ; then
 
   if test -r $srcdir/Data/Netlib/configure; then
     coin_subdirs="$coin_subdirs Data/Netlib"
@@ -21500,6 +21496,7 @@ echo "$as_me:$LINENO: checking whether project CoinUtils is available" >&5
 echo $ECHO_N "checking whether project CoinUtils is available... $ECHO_C" >&6
 
 coin_has_coinutils=notGiven
+coin_have_project_dir=no
 
 # check if user wants to skip project in any case
 
@@ -21517,6 +21514,7 @@ fi
 if test $coin_has_coinutils != skipping; then
   if test $PACKAGE_TARNAME = coinutils; then
     coin_has_coinutils=.
+    coin_have_project_dir=yes
   fi
 
 
@@ -21549,7 +21547,7 @@ if test $coin_has_coinutils = notGiven; then
 
     # let's assume that when installing into $prefix, then the user may have installed some other coin projects there before, so it's worth to have a look into there
     if test -d "$prefix"; then
-      PKG_CONFIG_PATH="$prefix/lib//pkgconfig:$PKG_CONFIG_PATH"
+      PKG_CONFIG_PATH="$prefix/lib/pkgconfig:$PKG_CONFIG_PATH"
     fi
 
 
@@ -21561,7 +21559,7 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
        fi
-       PKG_CONFIG_PATH="$withval/lib//pkgconfig:$PKG_CONFIG_PATH"
+       PKG_CONFIG_PATH="$withval/lib/pkgconfig:$PKG_CONFIG_PATH"
 
 fi;
 
@@ -21591,10 +21589,9 @@ fi
 # if not found yet, check if project is available in present directory
 if test "$coin_has_coinutils" = notGiven; then
   if test -d $srcdir//CoinUtils; then
-    coin_pkg_is_here=no
-     coin_pkg_is_here=yes
+     coin_have_project_dir=yes
 
-    if test $coin_pkg_is_here = yes; then
+    if test $coin_have_project_dir = yes; then
       coin_has_coinutils=/CoinUtils
     fi
   fi
@@ -21605,9 +21602,7 @@ echo "${ECHO_T}$coin_has_coinutils" >&6
 
 echo "$as_me:$LINENO: checking whether project CoinUtils need to be configured" >&5
 echo $ECHO_N "checking whether project CoinUtils need to be configured... $ECHO_C" >&6
-if test "$coin_has_coinutils" != skipping &&
-   test "$coin_has_coinutils" != notGiven &&
-   test "$coin_has_coinutils" != installed; then
+if test "$coin_have_project_dir" = yes ; then
 
   if test -r $srcdir//CoinUtils/configure; then
     coin_subdirs="$coin_subdirs CoinUtils"
@@ -21631,6 +21626,7 @@ echo "$as_me:$LINENO: checking whether project Clp is available" >&5
 echo $ECHO_N "checking whether project Clp is available... $ECHO_C" >&6
 
 coin_has_clp=notGiven
+coin_have_project_dir=no
 
 # check if user wants to skip project in any case
 
@@ -21648,6 +21644,7 @@ fi
 if test $coin_has_clp != skipping; then
   if test $PACKAGE_TARNAME = clp; then
     coin_has_clp=.
+    coin_have_project_dir=yes
   fi
 
 
@@ -21680,7 +21677,7 @@ if test $coin_has_clp = notGiven; then
 
     # let's assume that when installing into $prefix, then the user may have installed some other coin projects there before, so it's worth to have a look into there
     if test -d "$prefix"; then
-      PKG_CONFIG_PATH="$prefix/lib//pkgconfig:$PKG_CONFIG_PATH"
+      PKG_CONFIG_PATH="$prefix/lib/pkgconfig:$PKG_CONFIG_PATH"
     fi
 
 
@@ -21692,7 +21689,7 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
        fi
-       PKG_CONFIG_PATH="$withval/lib//pkgconfig:$PKG_CONFIG_PATH"
+       PKG_CONFIG_PATH="$withval/lib/pkgconfig:$PKG_CONFIG_PATH"
 
 fi;
 
@@ -21722,10 +21719,9 @@ fi
 # if not found yet, check if project is available in present directory
 if test "$coin_has_clp" = notGiven; then
   if test -d $srcdir//Clp; then
-    coin_pkg_is_here=no
-     coin_pkg_is_here=yes
+     coin_have_project_dir=yes
 
-    if test $coin_pkg_is_here = yes; then
+    if test $coin_have_project_dir = yes; then
       coin_has_clp=/Clp
     fi
   fi
@@ -21736,9 +21732,7 @@ echo "${ECHO_T}$coin_has_clp" >&6
 
 echo "$as_me:$LINENO: checking whether project Clp need to be configured" >&5
 echo $ECHO_N "checking whether project Clp need to be configured... $ECHO_C" >&6
-if test "$coin_has_clp" != skipping &&
-   test "$coin_has_clp" != notGiven &&
-   test "$coin_has_clp" != installed; then
+if test "$coin_have_project_dir" = yes ; then
 
   if test -r $srcdir//Clp/configure; then
     coin_subdirs="$coin_subdirs Clp"
